#!/usr/local/bin/bash

KARFILE=${KARFILE:-Karfile}

if [ ! -f $KARFILE ]; then
	echo "No Karfile found."
	exit 1
fi

hashbang=$(head -n 1 $KARFILE)

if [[ $hashbang == *"bash"* ]]; then
	$(dirname $(realpath "$0"))/kar.sh "$@"
elif [[ $hashbang == *"python"* ]]; then
	$(dirname $(realpath "$0"))/kar.py "$@"
else
	echo "Unable to figure out langauge using Karfile's hashbang"
	exit 1
fi
