#!/usr/local/bin/bash

source $(dirname $(realpath "$0"))/help.sh

if [ ! -f Karfile ]; then
	echo "No Karfile found."
	exit 1
fi

source Karfile

tasks=$(declare -F | cut -d' ' -f3 | grep "task-" | \
	awk '{gsub("task-",""); print}')

if [ $# -eq 0 ]; then
    echo "Tasks:"
	help Karfile
    exit 0
fi

cmd="$1"
shift 1

for task in $tasks; do
	if [ "$cmd" = "$task" ]; then
		task-$cmd $@
		exit 0
	fi
done

if [ "$cmd" = "help" ]; then
	help Karfile
	exit 0
fi

echo "Task $cmd" not found.
exit 1
